version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: typa_crediCorp
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - .:/app
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DB_MONGO_URL: ${DB_MONGO_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
